import "./globals.css";

import type { Metadata } from "next";

import Header from "@/components/header";

import { Footer } from "@/components/footer";
import { Geist, Geist_Mono } from "next/font/google";

import { ThreeProvider } from "@/components/three-provider";
import { ConvexClientProvider } from "./convex-client-provider";
import { AnimationProvider } from "@/components/animation-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AnimationProvider>
          <ThreeProvider>
            <ConvexClientProvider>
              <Header />
              {children}
              <Footer />
            </ConvexClientProvider>
          </ThreeProvider>
        </AnimationProvider>
      </body>
    </html>
  );
}
